import { Box } from "@chakra-ui/react";
import Head from "next/head";

import Header from "../components/header";
import Footer from "../components/footer";
import { getResiduos } from "../lib/residuosApi";
import Login from "../components/login";

export default function Home(props) {
  return (
    <>
      <Head>
        <title>LOGISTICA REVERSA | Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box height="100vh" display="flex" flexDirection="column">
        <Header residuos={props.data} />
        <Login />
        <Footer />
      </Box>
    </>
  );
}

export async function getStaticProps(context) {
  try {
    const residuos = await getResiduos(true);
    return {
      props: residuos,
    };
  } catch (error) {
    return {
      props: {},
    };
  }
}
