import Head from "next/head";
import Header from "../components/header";
import Footer from "../components/footer";
import Projeto from "../components/projeto";
import { getResiduos } from "../lib/residuosApi";

export default function (props) {
  return (
    <>
      <Head>
        <title>LOGISTICA REVERSA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header residuos={props.data} />
      <Projeto />
      <Footer />
    </>
  );
}
export async function getStaticProps(context) {
  try {
    const residuos = await getResiduos(true);
    return {
      props: residuos,
    };
  } catch (error) {
    console.log(error);
    return {
      props: {},
    };
  }
}
